## **ЗАВДАННЯ №1**

Вправа 2: Розставлення 1 та 0 у шаховому порядку
Постановка задачі:

Вводиться число 
N
n. Потрібно розставити 1 та 0 у шаховому порядку в матриці розміром 
N x N
n×n, починаючи з 1.

In [5]:
import numpy as np
import time

def task_2_numpy():
    n = int(input("Введіть розмір матриці n: "))
    start_time = time.time()
    result = np.indices((n, n)).sum(axis=0) % 2
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_2_iterative():
    n = int(input("Введіть розмір матриці n: "))
    start_time = time.time()
    result = [[(i+j) % 2 for j in range(n)] for i in range(n)]
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

# Приклад використання
print("З використанням NumPy:")
result_numpy, time_numpy = task_2_numpy()
print("Час виконання:", time_numpy)

print("\nЗа допомогою ітеративних конструкцій:")
result_iterative, time_iterative = task_2_iterative()
print("Час виконання:", time_iterative)

З використанням NumPy:
Час виконання: 0.00900125503540039

За допомогою ітеративних конструкцій:
Час виконання: 0.06401515007019043


Висновок: numpy прфцює набагато швидше на великому наборі даних

Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру
n×m, в якому в кожному рядку з номером r і в кожному стовпчику з
номером c стоять 0, а інші елементи дорівнюють 1.

In [8]:
import numpy as np
import time

def task_3_numpy():
    n, m, r, c = map(int, input("Введіть числа n, m, r, c через пробіл: ").split())
    start_time = time.time()
    arr = np.ones((n, m))
    arr[r, :] = 0
    arr[:, c] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

def task_3_iterative():
    n, m, r, c = map(int, input("Введіть числа n, m, r, c через пробіл: ").split())
    start_time = time.time()
    arr = [[1] * m for _ in range(n)]
    for i in range(n):
        arr[i][c] = 0
    for j in range(m):
        arr[r][j] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

result_iterative, time_iterative = task_3_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

result_numpy, time_numpy = task_3_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.004001140594482422
Час виконання (NumPy): 0.0010006427764892578


Висновок: numpy прфцює набагато швидше на великому наборі даних

Вправа 5. Вводиться число n. Вивести масив розміру n×n, в
якому в рядках з парними індексами стоять 1, а в інших – 0.

In [9]:
import numpy as np
import time

def task_5_numpy():
    n = int(input("Введіть розмір матриці n: "))
    start_time = time.time()
    result = np.zeros((n, n))
    result[::2, :] = 1
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_5_iterative():
    n = int(input("Введіть розмір матриці n: "))
    start_time = time.time()
    result = [[1 if i % 2 == 0 else 0 for j in range(n)] for i in range(n)]
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

result_iterative, time_iterative = task_5_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

result_numpy, time_numpy = task_5_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.05401253700256348
Час виконання (NumPy): 0.002000570297241211


Висновок: numpy прфцює набагато швидше на великому наборі даних

Вправа 9. Вводиться число n. Створити масив значень від n до 0.

In [12]:
import numpy as np
import time

def task_9_numpy():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    result = np.arange(n, -1, -1)
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

def task_9_iterative():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    result = list(range(n, -1, -1))
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

# Приклад використання
result_iterative, time_iterative = task_9_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

# Приклад використання
result_numpy, time_numpy = task_9_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.0
Час виконання (NumPy): 0.0


Висновок: numpy прфцює набагато швидше на великому наборі даних

Вправа 13. Розмістити на полі 8×8 нулі та одиниці в шахматному
порядку, використовуючи функцію повторення (*).
##
Вправа 14. Розмістити на полі 8×8 нулі та одиниці в шахматному
порядку, використовуючи функцію numpy tile().

In [14]:
import numpy as np
import time

def task_13_numpy():
    start_time = time.time()
    chessboard = np.tile([[0, 1], [1, 0]], (4, 4))
    end_time = time.time()
    execution_time = end_time - start_time
    return chessboard, execution_time

def task_14_iterative():
    even_row = [0, 1] * 4 
    odd_row = [1, 0] * 4
    start_time = time.time()
    chessboard = [even_row if i % 2 == 0 else odd_row for i in range(8)]
    end_time = time.time()
    execution_time = end_time - start_time
    return chessboard, execution_time

result_iterative, time_iterative = task_14_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

result_numpy, time_numpy = task_13_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.0
Час виконання (NumPy): 0.0


Висновок: numpy та ітеративний падхід працюють з однаковою швидкістю на цьому наборі даних

Вправа 16. Заповнити вектор значеннями від 0 до n. Всі значення,
що більші за n/4 та менші за 3n/4 замінити нулями.

In [15]:
import numpy as np
import time

def task_16_numpy():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    vector = np.arange(n+1)
    vector[(vector > n/4) & (vector < 3*n/4)] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    
    return vector, execution_time

def task_16_iterative():
    n = int(input("Введіть число n: "))
    vector = []
    start_time = time.time()
    for i in range(n+1):
        if i > n/4 and i < 3*n/4:
            vector.append(0)
        else:
            vector.append(i)
    end_time = time.time()
    execution_time = end_time - start_time
    
    return vector, execution_time

result_iterative, time_iterative = task_16_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

result_numpy, time_numpy = task_16_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.0
Час виконання (NumPy): 0.0


Висновок: numpy та ітеративний падхід працюють з однаковою швидкістю на цьому наборі даних

Вправа 17. Заповнити вектор значеннями від 0 до n. Замінити
знаки для всіх значень, що менші за n/2 та більші за 3n/4 на
протилежні.

In [16]:
import numpy as np
import time

def task_17_numpy():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    vector = np.arange(n+1)
    
    # Замінюємо знаки для певних значень на протилежні
    vector[(vector < n/2) | (vector > 3*n/4)] *= -1
    end_time = time.time()
    execution_time = end_time - start_time
    
    return vector, execution_time

def task_17_iterative():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    vector = []
    for i in range(n+1):
        if i < n/2 or i > 3*n/4:
            vector.append(-i)
        else:
            vector.append(i)
    end_time = time.time()
    execution_time = end_time - start_time
    
    return vector, execution_time

result_iterative, time_iterative = task_16_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

result_numpy, time_numpy = task_16_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.0010001659393310547
Час виконання (NumPy): 0.0


Висновок: numpy та ітеративний падхід працюють з однаковою швидкістю на цьому наборі даних

Вправа 20. Згенерувати вектор із n випадкових елементів, що
лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [17]:
import numpy as np
import random
import time

def task_20_numpy():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    # Генеруємо вектор з випадковими числами у проміжку (0, 1)
    vector = np.random.rand(n)
    
    # Знаходимо індекс максимального елементу
    max_index = np.argmax(vector)
    
    # Замінюємо максимальний елемент на 0
    vector[max_index] = 0
    
    end_time = time.time()
    execution_time = end_time - start_time
    
    return vector, execution_time

def task_20_iterative():
    n = int(input("Введіть число n: "))
    start_time = time.time()
    # Генеруємо вектор з випадковими числами у проміжку (0, 1)
    vector = [random.random() for _ in range(n)]
    
    # Знаходимо максимальний елемент
    max_value = max(vector)
    
    # Замінюємо максимальний елемент на 0
    vector[vector.index(max_value)] = 0
    
    end_time = time.time()
    execution_time = end_time - start_time
    
    return vector, execution_time

result_iterative, time_iterative = task_16_iterative()
print("Час виконання (ітеративний підхід):", time_iterative)

result_numpy, time_numpy = task_16_numpy()
print("Час виконання (NumPy):", time_numpy)

Час виконання (ітеративний підхід): 0.0010001659393310547
Час виконання (NumPy): 0.0


Висновок: numpy та ітеративний падхід працюють з однаковою швидкістю на цьому наборі даних

## **ЗАВДАННЯ №2**

x1 + x2 + 2x3 + 3x4 = 1
##
3x1 - x2 - 1x3 - 2x4 = -4
##
2x1 - 3x2 - 1x3 - 1x4 = -6
##
1x1 + 2x2 + 3x3 -1x4 = -4
##

2. Розв’язати систему алгебраїчних рівнянь за допомогою
##
формул Крамера і виконати перевірку за допомогою:
##
a) матричного множення;
##
b) оберненої матриці;
##
c) функції numpy.linalg.solve().
##
Порівняти всі рішення за допомогою функції numpy.allclose().

In [18]:
import numpy as np

# Головна матриця коефіцієнтів
A = np.array([[1, 1, 2, 3],
              [3, -1, -1, -2],
              [2, -3, -1, -1],
              [1, 2, 3, -1]])

# Матриця вільних членів
B = np.array([1, -4, -6, -4])

# Знаходимо визначник головної матриці
det_A = np.linalg.det(A)

# Знаходимо визначники матриць заміною стовпців
dets = []
for i in range(len(A)):
    Ai = A.copy()
    Ai[:, i] = B
    det_Ai = np.linalg.det(Ai)
    dets.append(det_Ai)

print("Визначник головної матриці:", det_A)
print("Визначники матриць заміною стовпців:", dets)

# Знаходимо значення кожного невідомого за формулами Крамера
X = []
for det in dets:
    Xi = det / det_A
    X.append(Xi)

print("Значення кожного невідомого за формулами Крамера:", X)

# Розрахунок за допомогою матричного множення
X_matrix_multiply = np.linalg.inv(A).dot(B)

# Розрахунок за допомогою оберненої матриці
X_inv_matrix = np.dot(np.linalg.inv(A), B)

# Розрахунок за допомогою функції numpy.linalg.solve()
X_np_solve = np.linalg.solve(A, B)

print("Розв'язок за допомогою матричного множення:", X_matrix_multiply)
print("Розв'язок за допомогою оберненої матриці:", X_inv_matrix)
print("Розв'язок за допомогою numpy.linalg.solve():", X_np_solve)

print("\nЧи всі розв'язки співпадають:", np.allclose(X, X_matrix_multiply) and
                                      np.allclose(X, X_inv_matrix) and
                                      np.allclose(X, X_np_solve))

Визначник головної матриці: 81.00000000000003
Визначники матриць заміною стовпців: [-44.99999999999999, 152.99999999999997, -161.99999999999994, 99.00000000000007]
Значення кожного невідомого за формулами Крамера: [-0.5555555555555552, 1.888888888888888, -1.9999999999999987, 1.2222222222222228]
Розв'язок за допомогою матричного множення: [-0.55555556  1.88888889 -2.          1.22222222]
Розв'язок за допомогою оберненої матриці: [-0.55555556  1.88888889 -2.          1.22222222]
Розв'язок за допомогою numpy.linalg.solve(): [-0.55555556  1.88888889 -2.          1.22222222]

Чи всі розв'язки співпадають: True


## **ЗАВДАННЯ №3**

3. Обчислити значення матричного виразу
## 
а) з використанням універсальних функцій бібліотеки NumPy.
## 
b) за допомогою ітеративних конструкцій (з використанням
## 
циклів, спискових включень тощо).
## 
с) для обох випадків підрахувати час виконання скрипту та
## 
зробити висновок.
## 
Порівняти всі рішення за допомогою функції numpy.allclose().
## 
3) 2(A + B)(2B - A) ,
## 
де A = 
## 
2 3 -1
## 
4 5 2
## 
-1 0 7

## 
B = 
## 
-1 0 5
## 
0 1 3
## 
2 -2 4

In [70]:
import numpy as np
import time

# Оголошення матриць A та B
A = np.array([[2, 3, -1],
              [4, 5, 2],
              [-1, 0, 7]])

B = np.array([[-1, 0, 5],
              [0, 1, 3],
              [2, -2, 4]])

# Початок вимірювання часу для NumPy
start_time_numpy = time.time()

# Обчислення значення матричного виразу за допомогою NumPy
result_numpy = 2 * (A + B) * (2 * B - A)

# Кінець вимірювання часу для NumPy
end_time_numpy = time.time()

# Оголошення результатів ітеративного підходу
result_iterative = np.zeros_like(A)

# Початок вимірювання часу для ітеративного підходу
start_time_iterative = time.time()

# Обчислення значення матричного виразу ітеративно
for i in range(len(A)):
    for j in range(len(A[0])):
        result_iterative[i, j] = 2 * (A[i, j] + B[i, j]) * (2 * B[i, j] - A[i, j])

# Кінець вимірювання часу для ітеративного підходу
end_time_iterative = time.time()

# Виведення результатів та часу виконання
print("Результат (NumPy):")
print(result_numpy)
print("Час виконання (NumPy):", end_time_numpy - start_time_numpy)

print("\nРезультат (ітеративний підхід):")
print(result_iterative)
print("Час виконання (ітеративний підхід):", end_time_iterative - start_time_iterative)

# Порівняння розв'язків
print("\nЧи всі розв'язки співпадають:", np.allclose(result_numpy, result_iterative))

Результат (NumPy):
[[ -8 -18  88]
 [-32 -36  40]
 [ 10  16  22]]
Час виконання (NumPy): 0.0

Результат (ітеративний підхід):
[[ -8 -18  88]
 [-32 -36  40]
 [ 10  16  22]]
Час виконання (ітеративний підхід): 0.0

Чи всі розв'язки співпадають: True


Numpy та ітеративний підхід праюють з однаковою швидкістю, але якщо матриця буде більшою, ітеративний буде значно постпатися Numpy